-- INSIGHT. 테크 블로그 관점 아카이브 — Supabase 스키마
-- Supabase 대시보드 → SQL Editor 에 통째로 붙여 넣고 Run. 여러 번 실행해도 안전하다.
-- 원문 전체가 들어 있으므로 외부 공개 금지: RLS 를 켜고 정책을 두지 않는다 → 서버(service_role)만 읽고 쓴다.

-- 1) 글 한 건 = 수집 원문 + 상태(포함/제외/대기) + 분석·가이드·분류 결과
create table if not exists public.articles (
  id               bigint generated by default as identity primary key,
  company_id       text        not null,
  title            text        not null,
  url              text        not null unique,
  published_at     timestamptz not null,
  content_html     text        not null default '',
  status           text        not null default 'pending' check (status in ('pending', 'included', 'excluded')),
  exclusion_reason text,
  learning         jsonb,
  reading_guide    jsonb,
  thumbnail_url    text,          -- null = 아직 안 찾음, '' = 찾아봤지만 없음
  attempts         int         not null default 0,  -- 자동 처리 시도 횟수(실패가 반복되면 건너뛴다)
  created_at       timestamptz not null default now()
);
create index if not exists articles_status_published on public.articles (status, published_at desc);

alter table public.articles enable row level security;
-- 정책 없음 = anon·authenticated 는 접근 불가. 서버의 service_role 키만 RLS 를 우회한다.

-- 2) 자동 실행이 겹치지 않게 하는 잠금 (예약 작업이 이전 실행이 끝나기 전에 또 깨워도 한 번만 돈다)
create table if not exists public.job_locks (
  name         text primary key,
  locked_until timestamptz not null default 'epoch'
);
alter table public.job_locks enable row level security;

create or replace function public.try_lock(lock_name text, seconds int)
returns boolean language plpgsql security definer set search_path = public as $$
declare got boolean;
begin
  insert into job_locks (name) values (lock_name) on conflict (name) do nothing;
  update job_locks set locked_until = now() + make_interval(secs => seconds)
   where name = lock_name and locked_until < now()
  returning true into got;
  return coalesce(got, false);
end $$;

create or replace function public.release_lock(lock_name text)
returns void language sql security definer set search_path = public as $$
  update job_locks set locked_until = 'epoch' where name = lock_name;
$$;

-- 3) 기존 데이터를 id 그대로 옮긴 뒤, 새 글 번호가 그다음부터 이어지게 맞춘다
create or replace function public.reset_articles_id_seq()
returns void language sql security definer set search_path = public as $$
  select setval(pg_get_serial_sequence('public.articles', 'id'), coalesce((select max(id) from articles), 0) + 1, false);
$$;

-- 함수는 서버(service_role)만 부른다
revoke execute on function public.try_lock(text, int) from public, anon, authenticated;
revoke execute on function public.release_lock(text) from public, anon, authenticated;
revoke execute on function public.reset_articles_id_seq() from public, anon, authenticated;
grant execute on function public.try_lock(text, int) to service_role;
grant execute on function public.release_lock(text) to service_role;
grant execute on function public.reset_articles_id_seq() to service_role;
